67 complete tests
MagicalGlove/ExamProjectSoft2ndSem pull request #68
Opened 2024-12-02 10:53 UTC by MagicalGlove

2024-12-02 10:54 UTC, SMerved requested changes
bad

2024-12-02 13:46 UTC, SMerved commented on Project/api/src/tests/unitTests/db/order.test/acceptCompleteAD.test.ts
> +        jest.spyOn(orderRepository, 'findOne').mockResolvedValue({
Should move mock object into a separate file, quite difficult to read.

2024-12-02 13:46 UTC, SMerved commented on Project/api/src/tests/unitTests/db/order.test/acceptReject.test.ts
> +            'Han har bestilt bearnaise pizza, ewww :vomit:'
There is nothing wrong with bearnaise pizza, remove this heresy.

2024-12-02 13:46 UTC, SMerved commented on Project/api/src/tests/unitTests/db/order.test/calculate.test.ts
There are a number of large mock objects in this file, should be moved into separate file for readability.
The dummyOrder reassignments could potentially be moved into a function.

2024-12-02 13:46 UTC, SMerved commented on Project/api/src/tests/unitTests/db/order.test/calculate.test.ts
> +        dummyOrder = {
Could be useful with a comment to explain the setHours data, as it is not really clear why its being set to specific values, and what it means.

2024-12-02 13:46 UTC, SMerved commented on Project/api/src/tests/unitTests/db/order.test/order.test.ts
This is not part of this particular pull request, but relevant for this file:
The create order test has two large mock objects, which should be moved into a separate file for readability.
Furthermore the test creates an order from a mockOrder, but then creates a new mock order (orderData) to compare it to. It should expect the returned order from the create order function to match the initial mockOrder instead.

2024-12-02 13:46 UTC, SMerved commented on Project/api/src/tests/unitTests/db/order.test/retrieveOrders.test.ts
> +    it('should handle errors and return null', async () => {
If the database returns an error, we shouldn't return null, we should return the error and let the caller handle it.

2024-12-02 13:46 UTC, SMerved commented on Project/api/src/tests/unitTests/db/order.test/retrieveOrders.test.ts
> +        const orders = await orderAndFeedbackRepository.GetAllOrdersById('672de88ff54107237ff75565');
Hardcoded id value, unclear where its coming from, and why we are certain this should exist in the database and return a successful result.

2024-12-02 13:46 UTC, SMerved commented on Project/api/src/tests/unitTests/db/restaurants.test.ts
> +        const restaurantRepository = AppDataSource.getMongoRepository(Restaurant);
Unnecesarry to initialize repositories in beforeEach, should just be done once at the top level.

2024-12-02 13:46 UTC, SMerved commented on Project/api/src/tests/unitTests/db/restaurants.test.ts
There is no test for if the function returns an error.

2024-12-02 13:46 UTC, SMerved commented on Project/api/src/tests/unitTests/db/user.test.ts
> +        const userRepository = AppDataSource.getMongoRepository(User);
Initialize at top level, not in beforeEach.

2024-12-02 13:46 UTC, SMerved commented on Project/api/src/tests/unitTests/db/user.test.ts
> +        // Mock Addresses
Not an address.

2024-12-02 13:46 UTC, SMerved commented on Project/api/src/tests/unitTests/db/user.test.ts
> +        const addressRepository = AppDataSource.getMongoRepository(Address);
Top level initialization

2024-12-02 14:06 UTC, MagicalGlove commented on Project/api/src/tests/unitTests/api/order.test.ts
> +describe('Post /ordersById', () => {
This test exists, but was misplaced and therefore missed. It has now been moved to its appropriate placement!

2024-12-02 14:10 UTC, MagicalGlove commented on Project/api/src/tests/unitTests/api/utilities.test.ts
> +    it('calculates the deliveree pay correctly', async () => {
The authoree disagrees 🤷‍♂️

2024-12-02 14:26 UTC, SMerved commented on Project/api/src/tests/unitTests/db/order.test/calculate.test.ts
> +        // eslint-disable-next-line @typescript-eslint/no-unused-vars
You can use _ infront of variable names to let eslint/typescript know that the variable will not be used.
Thereby removing the need for disabling eslint.

2024-12-03 10:39 UTC, MagicalGlove commented on Project/api/src/tests/unitTests/db/order.test/calculate.test.ts
> +        // eslint-disable-next-line @typescript-eslint/no-unused-vars
Cap

2024-12-03 10:40 UTC, MagicalGlove commented on Project/api/src/tests/unitTests/db/order.test/calculate.test.ts
> +        // eslint-disable-next-line @typescript-eslint/no-unused-vars
![error](https://github.com/user-attachments/assets/288666a3-920e-4e6b-a8b8-c511117566bc)
Cap

2024-12-03 11:31 UTC, MagicalGlove commented on Project/api/src/tests/unitTests/db/order.test/acceptReject.test.ts
> +            'Han har bestilt bearnaise pizza, ewww :vomit:'
🤮

2024-12-03 11:33 UTC, SMerved approved these changes
good

2024-12-03 11:36 UTC, merged